ethereum:
  endpoint: "http://localhost:8545"
  engineAPI: "http://localhost:8551"
  jwtSecret: "./jwt.hex"

cometbft:
  endpoint: "http://localhost:26657"
  homeDir: "./cometbft_home"

bridge:
  listenAddr: "0.0.0.0:8080"
  logLevel: "info"
  enableBridging: true
