ethereum:
  endpoint: "http://geth:8545"
  engineAPI: "http://geth:8551"
  jwtSecret: "/app/jwt.hex"

cometbft:
  endpoint: "http://cometbft:26657"
  homeDir: "/app/cometbft_home"

bridge:
  listenAddr: "0.0.0.0:8080"
  healthAddr: "0.0.0.0:8081"
  stateFile: "/app/data/ethbft_state.json"
  appVersion: "0.0.5"
  logLevel: "debug"
  enableBridging: true
